//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SimpleAccount.Maps
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MyG_AdminEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MyG_AdminEntities object using the connection string found in the 'MyG_AdminEntities' section of the application configuration file.
        /// </summary>
        public MyG_AdminEntities() : base("name=MyG_AdminEntities", "MyG_AdminEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyG_AdminEntities object.
        /// </summary>
        public MyG_AdminEntities(string connectionString) : base(connectionString, "MyG_AdminEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MyG_AdminEntities object.
        /// </summary>
        public MyG_AdminEntities(EntityConnection connection) : base(connection, "MyG_AdminEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MyG_AdminModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="iDUser">Initial value of the IDUser property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="dataCriacao">Initial value of the DataCriacao property.</param>
        /// <param name="ultimoLogin">Initial value of the UltimoLogin property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="contacto">Initial value of the Contacto property.</param>
        /// <param name="dataNascimento">Initial value of the DataNascimento property.</param>
        /// <param name="iDUserCreator">Initial value of the IDUserCreator property.</param>
        public static User CreateUser(global::System.Int32 iDUser, global::System.String login, global::System.String password, global::System.DateTime dataCriacao, global::System.DateTime ultimoLogin, global::System.String nome, global::System.String contacto, global::System.DateTime dataNascimento, global::System.Int32 iDUserCreator)
        {
            User user = new User();
            user.IDUser = iDUser;
            user.Login = login;
            user.Password = password;
            user.DataCriacao = dataCriacao;
            user.UltimoLogin = ultimoLogin;
            user.Nome = nome;
            user.Contacto = contacto;
            user.DataNascimento = dataNascimento;
            user.IDUserCreator = iDUserCreator;
            return user;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUser
        {
            get
            {
                return _IDUser;
            }
            set
            {
                if (_IDUser != value)
                {
                    OnIDUserChanging(value);
                    ReportPropertyChanging("IDUser");
                    _IDUser = StructuralObject.SetValidValue(value, "IDUser");
                    ReportPropertyChanged("IDUser");
                    OnIDUserChanged();
                }
            }
        }
        private global::System.Int32 _IDUser;
        partial void OnIDUserChanging(global::System.Int32 value);
        partial void OnIDUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false, "Login");
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataCriacao
        {
            get
            {
                return _DataCriacao;
            }
            set
            {
                OnDataCriacaoChanging(value);
                ReportPropertyChanging("DataCriacao");
                _DataCriacao = StructuralObject.SetValidValue(value, "DataCriacao");
                ReportPropertyChanged("DataCriacao");
                OnDataCriacaoChanged();
            }
        }
        private global::System.DateTime _DataCriacao;
        partial void OnDataCriacaoChanging(global::System.DateTime value);
        partial void OnDataCriacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UltimoLogin
        {
            get
            {
                return _UltimoLogin;
            }
            set
            {
                OnUltimoLoginChanging(value);
                ReportPropertyChanging("UltimoLogin");
                _UltimoLogin = StructuralObject.SetValidValue(value, "UltimoLogin");
                ReportPropertyChanged("UltimoLogin");
                OnUltimoLoginChanged();
            }
        }
        private global::System.DateTime _UltimoLogin;
        partial void OnUltimoLoginChanging(global::System.DateTime value);
        partial void OnUltimoLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false, "Nome");
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Morada
        {
            get
            {
                return _Morada;
            }
            set
            {
                OnMoradaChanging(value);
                ReportPropertyChanging("Morada");
                _Morada = StructuralObject.SetValidValue(value, true, "Morada");
                ReportPropertyChanged("Morada");
                OnMoradaChanged();
            }
        }
        private global::System.String _Morada;
        partial void OnMoradaChanging(global::System.String value);
        partial void OnMoradaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Contacto
        {
            get
            {
                return _Contacto;
            }
            set
            {
                OnContactoChanging(value);
                ReportPropertyChanging("Contacto");
                _Contacto = StructuralObject.SetValidValue(value, false, "Contacto");
                ReportPropertyChanged("Contacto");
                OnContactoChanged();
            }
        }
        private global::System.String _Contacto;
        partial void OnContactoChanging(global::System.String value);
        partial void OnContactoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NIF
        {
            get
            {
                return _NIF;
            }
            set
            {
                OnNIFChanging(value);
                ReportPropertyChanging("NIF");
                _NIF = StructuralObject.SetValidValue(value, true, "NIF");
                ReportPropertyChanged("NIF");
                OnNIFChanged();
            }
        }
        private global::System.String _NIF;
        partial void OnNIFChanging(global::System.String value);
        partial void OnNIFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataNascimento
        {
            get
            {
                return _DataNascimento;
            }
            set
            {
                OnDataNascimentoChanging(value);
                ReportPropertyChanging("DataNascimento");
                _DataNascimento = StructuralObject.SetValidValue(value, "DataNascimento");
                ReportPropertyChanged("DataNascimento");
                OnDataNascimentoChanged();
            }
        }
        private global::System.DateTime _DataNascimento;
        partial void OnDataNascimentoChanging(global::System.DateTime value);
        partial void OnDataNascimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sexo
        {
            get
            {
                return _Sexo;
            }
            set
            {
                OnSexoChanging(value);
                ReportPropertyChanging("Sexo");
                _Sexo = StructuralObject.SetValidValue(value, true, "Sexo");
                ReportPropertyChanged("Sexo");
                OnSexoChanged();
            }
        }
        private global::System.String _Sexo;
        partial void OnSexoChanging(global::System.String value);
        partial void OnSexoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdate
        {
            get
            {
                return _LastUpdate;
            }
            set
            {
                OnLastUpdateChanging(value);
                ReportPropertyChanging("LastUpdate");
                _LastUpdate = StructuralObject.SetValidValue(value, "LastUpdate");
                ReportPropertyChanged("LastUpdate");
                OnLastUpdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdate;
        partial void OnLastUpdateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDUserCreator
        {
            get
            {
                return _IDUserCreator;
            }
            set
            {
                OnIDUserCreatorChanging(value);
                ReportPropertyChanging("IDUserCreator");
                _IDUserCreator = StructuralObject.SetValidValue(value, "IDUserCreator");
                ReportPropertyChanged("IDUserCreator");
                OnIDUserCreatorChanged();
            }
        }
        private global::System.Int32 _IDUserCreator;
        partial void OnIDUserCreatorChanging(global::System.Int32 value);
        partial void OnIDUserCreatorChanged();

        #endregion

    }

    #endregion

}
